### ISSUE TITLE
Dcs-bios 2 mqtt

### ISSUE THREAD

**Issue by MansM** [y2kiah/A-10C-CDU-Display#2]
How did you create the bridge between dcs-bios to mqtt?
Looked through your code but couldn't find it. Am looking for something so I can use a couple of microcontrollers to make some modular systems and connect it to dcs-bios over mqtt

**Comment by y2kiah** [comment]
that part is contained in a NodeRED project, I'll see if I can locate it and commit it to the project

**Comment by MansM** [comment]
That would be great

**Comment by y2kiah** [comment]
I committed the Node-RED json file. This requires some Node-RED plugins to be installed, from what I recall at least the UI plugin is required to use the output monitoring dashboard. Also remember to install Mosquitto or another MQTT server of your choice.
One of the NodeRED flows will pick up the DCS-BIOS UDP data stream and run it through a javascript function to parse it into more usable data structures for use downstream. This is several years old so I cannot attest to it working with the latest version of DCS-BIOS, but it shouldn't be too far off.
